'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{chromium}=require('playwright');
test('clear-day sky retains blue chroma, and the night sky is genuinely darker',async()=>{
 const browser=await chromium.launch({executablePath:process.env.QA_BROWSER||undefined,headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{const p=await browser.newPage();await p.setContent('<canvas width="32" height="32"></canvas>');await p.addScriptTag({content:fs.readFileSync(__dirname+'/../graphics/shaders.js','utf8')});
 const result=await p.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl',{antialias:false,preserveDrawingBuffer:true});if(!gl)throw Error('WebGL unavailable');const S=NeonCoastShaders,p=gl.createProgram();for(const [type,src]of [[gl.VERTEX_SHADER,S.skyVertex],[gl.FRAGMENT_SHADER,S.skyFragment]]){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.useProgram(p);const a=gl.getAttribLocation(p,'a_position'),b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.uniform3f(gl.getUniformLocation(p,'u_forward'),.4,.35,.8);gl.uniform3f(gl.getUniformLocation(p,'u_right'),0,0,0);gl.uniform3f(gl.getUniformLocation(p,'u_up'),0,0,0);const sample=night=>{gl.uniform1f(gl.getUniformLocation(p,'u_night'),night);gl.drawArrays(gl.TRIANGLES,0,3);const bytes=new Uint8Array(4);gl.readPixels(16,16,1,1,gl.RGBA,gl.UNSIGNED_BYTE,bytes);return Array.from(bytes);};return{day:sample(0),night:sample(1),error:gl.getError()};});
 console.log(JSON.stringify(result));assert.equal(result.error,0);assert.ok(result.day[2]-result.day[0]>50,'sunny sky must not tone-map to gray');assert.ok(result.day.slice(0,3).every(v=>v<250),'no clipped sky');assert.ok(result.night[0]+result.night[1]+result.night[2]<(result.day[0]+result.day[1]+result.day[2])*.5);
 }finally{await browser.close();}
});
