'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const S=require('../graphics/shaders.js'),G=require('../graphics/geometry.js');
let V;try{V=require('../graphics/vehicles.js')}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
const text=fs.readFileSync(__dirname+'/../game.js','utf8'),context={Math,Float32Array,Map};vm.createContext(context);
vm.runInContext(`const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const shade=(c,f)=>c.map(x=>x*f);${text.slice(text.indexOf('    class Builder{'),text.indexOf('    function gpuMesh')).replace(/\s*NeonCoastGeometry\.install\(Builder\);/,'')}globalThis.B=Builder;`,context);G.install(context.B);
function check(b){assert.ok(b.p.length>0);assert.equal(b.p.length,b.n.length);assert.equal(b.p.length,b.c.length);let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<b.p.length;i+=3){const n=b.n.slice(i,i+3);assert.ok(n.every(Number.isFinite));assert.ok(Math.abs(Math.hypot(...n)-1)<.01);for(let k=0;k<3;k++){const v=b.p[i+k];assert.ok(Number.isFinite(v));min[k]=Math.min(min[k],v);max[k]=Math.max(max[k],v);}}return {min,max,triangles:b.p.length/9};}
test('clear foreground haze stays below 2% at 100m and masks the far draw boundary',()=>{assert.ok(S.atmosphere,'export the actual shader atmosphere parameters');const p=S.atmosphere;const haze=d=>1-Math.exp(-Math.max(0,d-p.nearClear)*p.dayDensity);assert.ok(haze(100)<.02);assert.ok(haze(500)<.10);assert.ok(p.farStart>=1200&&p.farEnd<=1470);assert.ok(S.fragment.includes(String(p.dayDensity)));});
test('rounded cuboid has curved corner normals and the exact requested bounds',()=>{assert.equal(typeof G.roundedBox,'function');const b=new context.B();G.roundedBox(b,0,1,0,2,1,4,[.5,.5,.5],.1,3);const q=check(b);for(let k=0;k<3;k++){assert.ok(Math.abs(q.min[k]-[-1,.5,-2][k])<1e-6);assert.ok(Math.abs(q.max[k]-[1,1.5,2][k])<1e-6);}assert.ok(b.n.some(v=>Math.abs(v)>.1&&Math.abs(v)<.9));});
test('four high-detail car classes retain wheelbase and cockpit anchors with a cheaper body LOD',()=>{assert.ok(V);const expected={roadster:[.46,1.45,-.32,-.65],muscle:[.49,1.54,-.37,-.53],coupe:[.47,1.49,-.37,-.49],sport:[.42,1.56,-.37,-.36]};for(const [kind,p]of Object.entries(expected)){const car=V.build(context.B,G,0xba3e32,kind);const high=check(car.body),low=check(car.bodyLow);check(car.details);check(car.lamps);check(car.glass);assert.equal(car.wheelY,p[0]);assert.equal(car.wheelZ,p[1]);assert.equal(car.cockpit.driverX,p[2]);assert.ok(Math.abs(car.cockpit.wheelZ-p[3])<1e-6);assert.ok(high.triangles>low.triangles*2);assert.ok(high.triangles<22000);assert.ok(high.min[1]>.15&&high.max[1]<1.95);assert.ok(high.min[2]>-2.5&&high.max[2]<2.5);assert.equal(car.wheelIndex,['roadster','muscle','coupe','sport'].indexOf(kind));}});
test('vehicle generation is deterministic and does not consume the world RNG',()=>{assert.ok(V);const old=Math.random;Math.random=()=>{throw new Error('World RNG consumed')};try{const a=V.build(context.B,G,0xb93931,'coupe'),b=V.build(context.B,G,0xb93931,'coupe');assert.deepEqual(a.body.p,b.body.p);}finally{Math.random=old;}});
test('Art Deco shop bays and balconies contain curved geometry instead of only boxes',()=>{const A=require('../graphics/architecture.js');assert.equal(typeof A.arch,'function');const b=new context.B();A.arch(b,0,1,0,1,.13,.18,[.8,.7,.6,3]);const q=check(b);assert.ok(q.triangles>=64);assert.ok(b.n.some(v=>Math.abs(v)>.1&&Math.abs(v)<.9));assert.ok(q.max[1]<=2.14);});
test('coupe bonnet stays below the fender crown rather than forming transverse wheel humps',()=>{const car=V.build(context.B,G,0xba3e32,'coupe');let highest=0;for(let i=0;i<car.body.p.length;i+=3){const [x,y,z]=car.body.p.slice(i,i+3);if(Math.abs(x)<.70&&z< -1.2&&z> -1.8)highest=Math.max(highest,y);}assert.ok(highest<1.07,'bonnet center must remain flatter than the raised outer fender');});
